apiVersion: v1
kind: Namespace
metadata:
  name: survey-microservices-architecture
---
apiVersion: v1
kind: Service
metadata:
  name: survey-api-svc
  namespace: survey-microservices-architecture
spec:
  type: LoadBalancer
  selector:
    app: survey-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-api-dep
  namespace: survey-microservices-architecture
  labels:
    app: survey-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-api
  template:
    metadata:
      labels:
        app: survey-api
    spec:
      containers:
        - name: survey-api-pod
          image: __dockerImage__
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
          imagePullPolicy: Always
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: survey-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: survey-api-dep
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90