apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-api-dep
  namespace: survey-microservices-architecture
  labels:
    app: survey-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-api
  template:
    metadata:
      labels:
        app: survey-api
    spec:
      containers:
        - name: survey-api-pod
          image: __dockerImage__
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: ConnectionStrings__MongoDb
              value: "__mongoDbConnectionString__"
            - name: ConnectionStrings__Redis
              value: "__redisConnectionString__"
            - name: ConnectionStrings__ApplicationInsights
              value: "__applicationInsightsConnectionString__"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
          imagePullPolicy: Always
      restartPolicy: Always