apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-api-dep
  namespace: survey-microservices-architecture
  labels:
    app: survey-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-api
  template:
    metadata:
      labels:
        app: survey-api
    spec:
      containers:
        - name: survey-api-pod
          image: __dockerImage__
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: connectionStrings.MongoDb
              value: ""
            - name: connectionStrings.Redis
              value: ""
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
          imagePullPolicy: Always
      restartPolicy: Always
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%