apiVersion: v1
kind: Service
metadata:
  name: survey-api-svc
  namespace: survey-microservices-architecture
spec:
  type: LoadBalancer
  selector:
    app: survey-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80