name: Deploy to Kubernetes cluster

on:
  workflow_dispatch:
  push:
    paths:
      - survey-web/**
    branches:
      - "main"

jobs:
  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./survey-web
    env:
      DOCKER_IMAGE_NAME: registry.digitalocean.com/survey-microservices-architecture/survey-api:${{ github.sha }}
      USE_CDN: true

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
          cache: "npm"
          cache-dependency-path: ./survey-web

      - name: Install npm dependencies
        run: npm ci

      - uses: falnyr/replace-env-vars-action@master
        name: Replace variables in .env.production file
        env:
          apiUrl: ${{ secrets.API_URL }}
        with:
          filename: ./survey-web/.env.production

      - name: Build project
        run: npm run build

      - name: Upload build assets to Cloudinary CDN
        uses: ./.github/actions/cloudinary-uploader
        with:
          cloud-name: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          api-key: ${{ secrets.CLOUDINARY_API_KEY }}
          api-secret: ${{ secrets.CLOUDINARY_API_SECRET }}
          assets-path: survey-web/out/_next/static

      - name: Docker login
        run: docker login registry.digitalocean.com -u ${{ secrets.DIGITAL_OCEAN_REGISTRY_CREDENTIALS }} -p ${{ secrets.DIGITAL_OCEAN_REGISTRY_CREDENTIALS }}

      - name: Build Docker image
        run: docker image build -t ${{ env.DOCKER_IMAGE_NAME }} -f Dockerfile.prod .

      - name: Push Docker image
        run: docker image push ${{ env.DOCKER_IMAGE_NAME }}
  deploy-to-kubernetes:
    name: Deploy to Kubernetes cluster
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./survey-web
    env:
      DOCKER_IMAGE_NAME: registry.digitalocean.com/survey-microservices-architecture/survey-api:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - uses: falnyr/replace-env-vars-action@master
        name: Replace variables in K8s manifest
        env:
          dockerImage: ${{ env.DOCKER_IMAGE_NAME }}
        with:
          filename: ./survey-web/k8s/deployment.yml

      - uses: tale/kubectl-action@v1
        name: Setup Kubernetes cluster config
        with:
          base64-kube-config: ${{ secrets.DIGITAL_OCEAN_KUBE_CONFIG }}

      - name: Apply deployment on Kubernetes cluster
        run: kubectl apply -f ./k8s
